### ISSUE TITLE
Scheduled task to sync Rampart with Portal

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/noah#1]
We should add a `lastSyncedWithPortal` column (`BIT(1)`) to all entities in Noah (e.g., users, groups). Then our scheduled task will check to see if `lastModified > lastSyncedWithPortal` and perform the appropriate CRUD action.

**Comment by fitzyjoe** [comment]
Noah has entities?  Bit(1) compared with date?

**Comment by kevinmichaelchen** [comment]
Noah has entities for users and groups, and a join table for memberships. 

`lastSyncedWithPortal` should be a datetime, not a bit.
